#!/usr/bin/env ruby
# Creates a small TencleLang app skeleton outside NovaOS.
# Usage: ruby tools/ruby/new_tencle_app.rb Calculator

name = ARGV[0]
if name.nil? || name.strip.empty?
  warn "Usage: ruby tools/ruby/new_tencle_app.rb AppName"
  exit 1
end

safe = name.downcase.gsub(/[^a-z0-9_\-]/, "_")
root = File.expand_path("../..", __dir__)
apps_dir = File.join(root, "external_apps")
docs_dir = File.join(root, "docs", "apps")
Dir.mkdir(apps_dir) unless Dir.exist?(apps_dir)
Dir.mkdir(docs_dir) unless Dir.exist?(docs_dir)

app_path = File.join(apps_dir, "#{safe}.tlang")
doc_path = File.join(docs_dir, "#{safe}.md")

if File.exist?(app_path)
  warn "App already exists: #{app_path}"
  exit 1
end

File.write(app_path, <<~TLANG)
  int << func >>("#{name}")
  int << func >>("Created for NovaOS TencleLang")
TLANG

File.write(doc_path, <<~MD)
  # #{name}

  TencleLang app generated by Ruby.

  Source:

  ```text
  external_apps/#{safe}.tlang
  ```
MD

puts "Created #{app_path}"
puts "Created #{doc_path}"
